# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wba_99MdHn1KtXV0S6wv20GWeS2ZA2Ss
"""

from collections import deque
import copy

# GLOBAL COUNTERS
backtrack_calls = 0
backtrack_failures = 0

# READ SUDOKU FROM FILE
def read_sudoku(filename):
    board = []
    try:
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()
                if line:
                    board.append([int(x) for x in line])
        return board
    except FileNotFoundError:
        print(f"Error: {filename} not found.")
        return None

# PRINT BOARD
def print_board(board):
    for row in board:
        print(" ".join(map(str, row)))
    print()

# GET NEIGHBORS (Constraints)
def get_neighbors():
    neighbors = {}
    for r in range(9):
        for c in range(9):
            neighbors[(r, c)] = set()
            # Row and Column constraints
            for i in range(9):
                if i != c: neighbors[(r, c)].add((r, i))
                if i != r: neighbors[(r, c)].add((i, c))
            # 3x3 Box constraints
            box_r, box_c = 3 * (r // 3), 3 * (c // 3)
            for i in range(box_r, box_r + 3):
                for j in range(box_c, box_c + 3):
                    if (i, j) != (r, c):
                        neighbors[(r, c)].add((i, j))
    return neighbors

# INITIAL DOMAINS
def initialize_domains(board):
    domains = {}
    for r in range(9):
        for c in range(9):
            if board[r][c] == 0:
                domains[(r, c)] = set(range(1, 10))
            else:
                domains[(r, c)] = {board[r][c]}
    return domains

# AC-3 ALGORITHM (Arc Consistency)
def ac3(domains, neighbors):
    queue = deque([(xi, xj) for xi in domains for xj in neighbors[xi]])
    while queue:
        xi, xj = queue.popleft()
        if revise(domains, xi, xj):
            if len(domains[xi]) == 0:
                return False
            for xk in neighbors[xi]:
                if xk != xj:
                    queue.append((xk, xi))
    return True

def revise(domains, xi, xj):
    revised = False
    # Standard CSP Revise: Remove x from D(xi) if it has no consistent value in D(xj)
    for x in list(domains[xi]):
        # If there's no y in D(xj) such that x != y, remove x
        if all(x == y for y in domains[xj]):
            domains[xi].remove(x)
            revised = True
    return revised

# HEURISTICS (MRV & LCV)
def select_unassigned_variable(domains):
    # MRV: Minimum Remaining Values
    unassigned = [v for v in domains if len(domains[v]) > 1]
    if not unassigned:
        return None
    return min(unassigned, key=lambda var: len(domains[var]))

def order_domain_values(domains, var, neighbors):
    # LCV: Least Constraining Value
    # Sort values by how many options they rule out for neighbors (prefer fewer)
    def count_conflicts(value):
        count = 0
        for n in neighbors[var]:
            if value in domains[n]:
                count += 1
        return count
    return sorted(domains[var], key=count_conflicts)

# FORWARD CHECKING
def forward_check(domains, var, value, neighbors):
    # Optimization: Manual dictionary/set copy is faster than deepcopy
    new_domains = {v: set(d) for v, d in domains.items()}
    new_domains[var] = {value}

    for n in neighbors[var]:
        if value in new_domains[n]:
            new_domains[n].remove(value)
            if len(new_domains[n]) == 0:
                return None
    return new_domains

# BACKTRACKING SEARCH
def backtrack(domains, neighbors):
    global backtrack_calls, backtrack_failures
    backtrack_calls += 1

    # Check if assignment is complete
    if all(len(domains[v]) == 1 for v in domains):
        return domains

    var = select_unassigned_variable(domains)
    if var is None: return domains

    # Try values using LCV heuristic
    for value in order_domain_values(domains, var, neighbors):
        new_domains = forward_check(domains, var, value, neighbors)

        if new_domains is not None:
            # Maintain Arc Consistency (MAC)
            if ac3(new_domains, neighbors):
                result = backtrack(new_domains, neighbors)
                if result is not None:
                    return result

    backtrack_failures += 1
    return None

# MAIN SOLVER ENGINE
def solve_sudoku(filename):
    global backtrack_calls, backtrack_failures
    backtrack_calls = 0
    backtrack_failures = 0

    board = read_sudoku(filename)
    if not board: return

    neighbors = get_neighbors()
    domains = initialize_domains(board)

    # Pre-process with AC-3
    if not ac3(domains, neighbors):
        print(f" Initial AC-3 failed for {filename}")
        return

    result = backtrack(domains, neighbors)

    if result:
        print(f" Solution for {filename}:")
        solved_board = [[list(result[(r, c)])[0] for c in range(9)] for r in range(9)]
        print_board(solved_board)
        print(f"Backtrack Calls: {backtrack_calls}")
        print(f"Backtrack Failures: {backtrack_failures}")
        print("-" * 30)
    else:
        print(f" No solution found for {filename}")

if __name__ == "__main__":
    files = ["EASY.txt", "MEDIUM.txt", "HARD.txt", "HARD2.txt"]
    for f in files:
        solve_sudoku(f)